classDiagram

    direction LR

    class Function {
        <<Abstract>>
    }

    class ConstantFunction {
        DimX = 0
        DimU = 0
        DimY = 1
        Value : double
    }
    class MultiplyFunction {
        DimX = 0
        DimU = 1
        DimY = 1
        Factor : double
    }
    class AddFunction {
        DimX = 0
        DimU = 2
        DimY = 1
    }

    Function <|-- ConstantFunction
    Function <|-- MultiplyFunction
    Function <|-- AddFunction

    style Function fill:white