classDiagram

    direction TB

    class Model {
    }

    class Solver {
        <<Abstract>>
        Model : Model
        ContinuousStates : Dictionary~Block, double[]~
        Derivatives : Dictionary~Block, double[]~
        Inputs : Dictionary~Block, double[]~
        Outputs : Dictionary~Block, double[]~
        InputReadyFlags : Dictionary~Block, bool[]~
        Solve(timeStep : double, timeLimit : double) void
        InitializeStates() void
        ResetFlags() void
        AreAllInputsReady(block : Block) bool
        CalculateOutputs(time : double) void
        ForwardOutputs(block : Block) bool 
        CalculateDerivatives(time : doube) void
        IntegrateContinuousStates(timeStep : double) void
    }

    Model "1" --* Solver

    style Model fill:white