flowchart

    Gravity["<b>Constant</b><br/>(Value = -9.81)"]
    Damping["<b>Gain</b><br/>(Factor = -0.5)"]
    HitLowerLimit["<b>HitLowerLimit</b><br/>(Value = 0)"]
    Velocity["<b>IntegrateWithReset</b><br/>(Velocity)"]
    Position["<b>Integrate</b><br/>(Position)"]

    Gravity --derivative--> Velocity
    
    Damping --reset state--> Velocity --> Damping

    Velocity --derivative--> Position

    Position --> HitLowerLimit --reset flag--> Velocity