flowchart

    c1["<b>Constant</b><br/>(Value = 1)"] --reset state--> i
    c2["<b>Constant</b><br/>(Value = -0.3)"] --derivative---> i
    i["<b>IntegrateWithLowerLimit</b><br/>(Initial = 1, Limit = 0)"] --> r["<b>Record</b>"]