flowchart

    Szene --> Haus1
    Szene --> Haus2

    Haus1 --> Fenster1
    Haus1 --> Fenster2

    Fenster1 --> Rahmen1
    Fenster1 --> Glas1

    Fenster2 --> Rahmen2["..."]

    Haus2 --> Fenster3["..."]